#!/usr/bin/env bash

. common

$DIALOG --backtitle "Troubleshooting" --title "Troubleshooting" --menu "What is your problem?" 12 40 3 \
    "C" "Compiling problems" \
    "R" "Runtime problems" \
    "O" "Other problems"
    
$DIALOG --backtitle "Troubleshooting" --title "Compile problems" --menu "What is your problem?" 20 40 3 \
    "TODO" "TODO"