cmake_policy(SET CMP0091 NEW) # Enable [CMAKE_]MSVC_RUNTIME_LIBRARY

set(TF2BD_VERSION_MAJOR 1 CACHE STRING "TF2BD major version." FORCE)
set(TF2BD_VERSION_MINOR 2 CACHE STRING "TF2BD minor version." FORCE)
set(TF2BD_VERSION_PATCH 0 CACHE STRING "TF2BD patch version." FORCE)
