name: download_and_compile

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Download batch script from repo
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/PazerOP/tf2_bot_detector/raw/${{ github.sha }}/util/download_and_compile.bat"

    - name: Run batch script
      shell: cmd
      run: download_and_compile.bat
      env:
        TF2BD_DL_AND_COMPILE_SKIP_OPEN: 1
