name: download_and_compile

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  config:
    runs-on: windows-latest
    steps:
    - name: Download batch script from repo
      run: wget https://github.com/PazerOP/tf2_bot_detector/raw/${{ github.sha }}/util/download_and_compile.bat

    - name: Run batch script
      run: download_and_compile.bat
